version: '3'

services:
  web:
    build: .
    container_name: web
    command: bash -c "gunicorn bablo.wsgi -b 0.0.0.0:1499"
    volumes:
      - ./:/web
      - ./webapp/static:/web/webapp/static
      - ./webapp/media:/web/webapp/media
    environment:
      SERVER_IP: ${SERVER_IP}

  nginx:
    build: ./config/nginx/
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - web:web
    volumes:
      - ./config/nginx:/config/nginx
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./webapp:/web/webapp
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
