# Generated by Django 2.2.6 on 2019-10-21 11:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_ua', models.CharField(default='', max_length=100, verbose_name='Name_ua')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('icon', models.CharField(default='', max_length=50, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ReadPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField()),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/posts', verbose_name='Images')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('withdrawn', 'Withdrawn')], default='draft', max_length=1)),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Category')),
                ('tag', models.ManyToManyField(related_name='readposts', to='webapp.Tag')),
            ],
            options={
                'verbose_name': 'ReadPost',
                'verbose_name_plural': 'ReadPosts',
                'ordering': ('-date',),
            },
        ),
    ]
